name: PhotoSwiper
options:
  bundleIdPrefix: com.joehill
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
settings:
  base:
    MARKETING_VERSION: "0.1.2"
    CURRENT_PROJECT_VERSION: "3"
    SWIFT_VERSION: "5.10"
    CODE_SIGN_STYLE: Manual
    CODE_SIGNING_REQUIRED: NO
    CODE_SIGNING_ALLOWED: NO
targets:
  PhotoSwiper:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "**/Info.plist"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.joehill.photoswiper
        TARGETED_DEVICE_FAMILY: "1"
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Sources/App/Info.plist
  PhotoSwiperTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    dependencies:
      - target: PhotoSwiper
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.joehill.photoswiperTests
        GENERATE_INFOPLIST_FILE: YES
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  PhotoSwiper:
    build:
      targets:
        PhotoSwiper: all
        PhotoSwiperTests: [test]
    test:
      targets:
        - PhotoSwiperTests
      gatherCoverageData: false
